### ISSUE TITLE
oi.select 0.2.2 single selection doesn't update input value until blur event is executed

### ISSUE THREAD

**Issue by Serginho** [tamtakoe/oi.select#17] opened 2015-07-29 11:51 UTC
I'm using oi-select with single seleccion and the problem is the following:

Step-by-step:
1. I click inside the input and oi-select shows me all options values.
2. I click to select one option  and oi-select hides options but keeps the placeholder string and doesn't update input value.
3. I click outside the input (in any place) and the input loses focus and then the value is set

**Comment by tamtakoe** [comment] 2015-07-30 19:11
@Serginho try in v 0.2.3. What browser do you use?

**Comment by Serginho** [comment] 2015-07-30 19:25
chrome

El 30/7/2015 9:11 p. m., tamtakoe <notifications@github.com> escribió:
@Serginho try in v 0.2.3. What browser do you use?

---

**Comment by tamtakoe** [comment] 2015-08-01 12:10
@Serginho I can not repeat this case. What oi-select settings have been used?

**Comment by Serginho** [comment] 2015-08-03 08:45
@tamtakoe I'm using default settings.
I've downloaded 0.2.4 version and this is worse, when I click in a element, the element is removed of the list but the list doesn't hide and the element doesn't appear inside the input.
And in multiple selection mode, when you select several elements, and then removed it of the input, the last element is not added again to the list for a new selection.

**Comment by tamtakoe** [comment] 2015-08-04 04:13
@Serginho when list is not hide after adding or removing element it is not a bug, it is the behavior. It is well for small lists. But I looked at most of the multiselects, and came to the conclusion that it is better to do as you wrote. I push the changes to the master.

There is the problem with focus/blur in current version. I will fix it in future.

**Comment by tamtakoe** [comment] 2015-08-10 08:47
It fixed in 0.2.5

**Closed by tamtakoe** 2015-08-10 08:47 UTC
